
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/top 

module top(clock, reset, request1, request2, request3, request4,
     lfsr_seed, grant_o, bist_start, bist_end, signature_out,
     pass_fail);
  input clock, reset, request1, request2, request3, request4,
       bist_start;
  input [3:0] lfsr_seed;
  output [3:0] grant_o;
  output bist_end, pass_fail;
  output [7:0] signature_out;
  wire clock, reset, request1, request2, request3, request4, bist_start;
  wire [3:0] lfsr_seed;
  wire [3:0] grant_o;
  wire bist_end, pass_fail;
  wire [7:0] signature_out;
  wire [3:0] lsfr_in_bus_w;
  wire [2:0] uut_coda0;
  wire [2:0] uut_coda1;
  wire [2:0] uut_coda2;
  wire [2:0] uut_coda3;
  wire [3:0] input_mux_out_w;
  wire [1:0] uut_stato;
  wire [10:0] bist_controller_ncounter;
  wire [2:0] bist_controller_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17,
       bist_controller_n_114, bist_controller_reset_latch,
       bist_controller_toggle_r, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_101, n_102, n_104, n_105, n_106, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_125;
  wire n_126, n_127, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_153, n_154;
  wire n_160, n_162, n_165, n_166, scan_toggle_w, uut_fu1, uut_fu2,
       uut_fu3;
  wire uut_fu4, uut_n_0, uut_n_4, uut_n_6, uut_n_8, uut_n_10, uut_n_12,
       uut_n_14;
  wire uut_n_16, uut_n_18, uut_n_20, uut_n_22, uut_n_24, uut_n_26,
       uut_n_28, uut_n_30;
  wire uut_n_32, uut_n_34, uut_n_36, uut_n_38, uut_n_40, uut_n_42,
       uut_n_44, uut_n_46;
  wire uut_n_48, uut_n_50, uut_n_59, uut_n_60, uut_n_61, uut_n_63,
       uut_n_73, uut_n_84;
  wire uut_n_87, uut_n_89, uut_n_98, uut_n_102, uut_n_103, uut_n_104,
       uut_n_105, uut_n_106;
  wire uut_n_107, uut_n_108, uut_n_110, uut_n_111, uut_ru1, uut_ru2,
       uut_ru3, uut_ru4;
  wire uut_scan_w;
  DFSC1 \uut_coda0_reg[0] (.RN (n_50), .C (clock), .D (uut_n_84), .SD
       (lsfr_in_bus_w[3]), .SE (scan_toggle_w), .Q (uut_coda0[0]), .QN
       (uut_n_32));
  DFSC1 \uut_coda0_reg[1] (.RN (n_50), .C (clock), .D (uut_n_87), .SD
       (uut_n_32), .SE (scan_toggle_w), .Q (uut_coda0[1]), .QN
       (uut_n_28));
  DFSC1 \uut_coda0_reg[2] (.RN (n_50), .C (clock), .D (uut_n_89), .SD
       (uut_n_28), .SE (scan_toggle_w), .Q (uut_coda0[2]), .QN
       (uut_n_30));
  DFSC1 \uut_coda1_reg[0] (.RN (n_50), .C (clock), .D (uut_n_105), .SD
       (uut_n_30), .SE (scan_toggle_w), .Q (uut_coda1[0]), .QN
       (uut_n_50));
  DFSC1 \uut_coda1_reg[1] (.RN (n_50), .C (clock), .D (uut_n_107), .SD
       (uut_n_50), .SE (scan_toggle_w), .Q (uut_coda1[1]), .QN
       (uut_n_48));
  DFSC1 \uut_coda1_reg[2] (.RN (n_50), .C (clock), .D (uut_n_106), .SD
       (uut_n_48), .SE (scan_toggle_w), .Q (uut_coda1[2]), .QN
       (uut_n_46));
  DFSC1 \uut_coda2_reg[0] (.RN (n_50), .C (clock), .D (uut_n_110), .SD
       (uut_n_46), .SE (scan_toggle_w), .Q (uut_coda2[0]), .QN
       (uut_n_44));
  DFSC1 \uut_coda2_reg[1] (.RN (n_50), .C (clock), .D (uut_n_111), .SD
       (uut_n_44), .SE (scan_toggle_w), .Q (uut_coda2[1]), .QN
       (uut_n_42));
  DFSC1 \uut_coda2_reg[2] (.RN (n_50), .C (clock), .D (uut_n_108), .SD
       (uut_n_42), .SE (scan_toggle_w), .Q (uut_coda2[2]), .QN
       (uut_n_40));
  DFSC1 \uut_coda3_reg[0] (.RN (n_50), .C (clock), .D (uut_n_103), .SD
       (uut_n_40), .SE (scan_toggle_w), .Q (uut_coda3[0]), .QN
       (uut_n_36));
  DFSC1 \uut_coda3_reg[1] (.RN (n_50), .C (clock), .D (uut_n_102), .SD
       (uut_n_36), .SE (scan_toggle_w), .Q (uut_coda3[1]), .QN
       (uut_n_34));
  DFSC1 \uut_coda3_reg[2] (.RN (n_50), .C (clock), .D (uut_n_104), .SD
       (uut_n_34), .SE (scan_toggle_w), .Q (uut_coda3[2]), .QN
       (uut_n_38));
  DFSEC1 uut_fu1_reg(.RN (n_50), .C (clock), .D (uut_ru1), .E
       (uut_n_73), .SD (uut_n_38), .SE (scan_toggle_w), .Q (uut_fu1),
       .QN (uut_n_14));
  DFSEC1 uut_fu2_reg(.RN (n_50), .C (clock), .D (uut_ru2), .E
       (uut_n_73), .SD (uut_n_14), .SE (scan_toggle_w), .Q (uut_fu2),
       .QN (uut_n_18));
  DFSEC1 uut_fu3_reg(.RN (n_50), .C (clock), .D (uut_ru3), .E
       (uut_n_73), .SD (uut_n_18), .SE (scan_toggle_w), .Q (uut_fu3),
       .QN (uut_n_12));
  DFSEC1 uut_fu4_reg(.RN (n_50), .C (clock), .D (uut_ru4), .E
       (uut_n_73), .SD (uut_n_12), .SE (scan_toggle_w), .Q (uut_fu4),
       .QN (uut_n_16));
  DFSEC1 \uut_grant_reg[0] (.RN (n_50), .C (clock), .D (uut_n_63), .E
       (uut_n_98), .SD (uut_n_16), .SE (scan_toggle_w), .Q
       (grant_o[0]), .QN (uut_n_26));
  DFSEC1 \uut_grant_reg[1] (.RN (n_50), .C (clock), .D (uut_n_59), .E
       (uut_n_98), .SD (uut_n_26), .SE (scan_toggle_w), .Q
       (grant_o[1]), .QN (uut_n_24));
  DFSEC1 \uut_grant_reg[2] (.RN (n_50), .C (clock), .D (uut_n_60), .E
       (uut_n_98), .SD (uut_n_24), .SE (scan_toggle_w), .Q
       (grant_o[2]), .QN (uut_n_22));
  DFSEC1 \uut_grant_reg[3] (.RN (n_50), .C (clock), .D (uut_n_61), .E
       (uut_n_98), .SD (uut_n_22), .SE (scan_toggle_w), .Q
       (grant_o[3]), .QN (uut_n_20));
  DFSEC1 uut_ru1_reg(.RN (n_50), .C (clock), .D (input_mux_out_w[0]),
       .E (uut_stato[0]), .SD (uut_n_20), .SE (scan_toggle_w), .Q
       (uut_ru1), .QN (uut_n_8));
  DFSEC1 uut_ru2_reg(.RN (n_50), .C (clock), .D (input_mux_out_w[1]),
       .E (uut_stato[0]), .SD (uut_n_8), .SE (scan_toggle_w), .Q
       (uut_ru2), .QN (uut_n_10));
  DFSEC1 uut_ru3_reg(.RN (n_50), .C (clock), .D (input_mux_out_w[2]),
       .E (uut_stato[0]), .SD (uut_n_10), .SE (scan_toggle_w), .Q
       (uut_ru3), .QN (uut_n_6));
  DFSEC1 uut_ru4_reg(.RN (n_50), .C (clock), .D (input_mux_out_w[3]),
       .E (uut_stato[0]), .SD (uut_n_6), .SE (scan_toggle_w), .Q
       (uut_ru4), .QN (uut_n_4));
  TFSC1 \uut_stato_reg[0] (.RN (n_50), .C (clock), .SD (uut_n_4), .SE
       (scan_toggle_w), .Q (uut_n_0), .QN (uut_stato[0]));
  DFSC1 \uut_stato_reg[1] (.RN (n_50), .C (clock), .D (uut_n_73), .SD
       (uut_n_0), .SE (scan_toggle_w), .Q (uut_stato[1]), .QN
       (uut_scan_w));
  CLKIN3 g1435(.A (n_160), .Q (n_129));
  NAND20 g1889(.A (n_123), .B (n_147), .Q (pass_fail));
  NOR40 g1890(.A (signature_out[5]), .B (signature_out[4]), .C
       (signature_out[3]), .D (n_146), .Q (n_147));
  INV2 g1891(.A (n_145), .Q (n_146));
  NOR40 g1892(.A (signature_out[6]), .B (signature_out[2]), .C
       (signature_out[1]), .D (signature_out[0]), .Q (n_145));
  DF3 \bist_misr_dff_reg[6] (.C (clock), .D (n_144), .Q
       (signature_out[6]), .QN (n_51));
  INV3 g1894(.A (n_143), .Q (n_144));
  NOR21 g1895(.A (reset), .B (signature_out[5]), .Q (n_143));
  DF3 \bist_misr_dff_reg[5] (.C (clock), .D (n_142), .Q
       (signature_out[5]), .QN (UNCONNECTED));
  INV3 g1897(.A (n_141), .Q (n_142));
  NOR21 g1898(.A (reset), .B (signature_out[4]), .Q (n_141));
  DF3 \bist_misr_dff_reg[4] (.C (clock), .D (n_140), .Q
       (signature_out[4]), .QN (UNCONNECTED0));
  NAND22 g1900(.A (n_139), .B (n_50), .Q (n_140));
  XOR31 g1901(.A (signature_out[3]), .B (uut_scan_w), .C (n_123), .Q
       (n_139));
  DF3 \bist_misr_dff_reg[3] (.C (clock), .D (n_138), .Q
       (signature_out[3]), .QN (UNCONNECTED1));
  NAND22 g1903(.A (n_137), .B (n_50), .Q (n_138));
  XOR31 g1904(.A (signature_out[2]), .B (grant_o[0]), .C (n_123), .Q
       (n_137));
  DF3 \bist_misr_dff_reg[2] (.C (clock), .D (n_136), .Q
       (signature_out[2]), .QN (UNCONNECTED2));
  NAND22 g1906(.A (n_135), .B (n_50), .Q (n_136));
  XOR31 g1907(.A (signature_out[1]), .B (grant_o[1]), .C (n_123), .Q
       (n_135));
  MUX22 g1908(.A (request4), .B (lsfr_in_bus_w[3]), .S (n_133), .Q
       (input_mux_out_w[3]));
  DFS1 \bist_lfsr_dff_reg[3] (.C (clock), .D (lsfr_in_bus_w[2]), .SD
       (lfsr_seed[3]), .SE (reset), .Q (lsfr_in_bus_w[3]), .QN
       (UNCONNECTED3));
  MUX22 g1910(.A (request3), .B (lsfr_in_bus_w[2]), .S (n_133), .Q
       (input_mux_out_w[2]));
  MUX22 g1911(.A (request2), .B (lsfr_in_bus_w[1]), .S (n_133), .Q
       (input_mux_out_w[1]));
  MUX22 g1912(.A (request1), .B (lsfr_in_bus_w[0]), .S (n_133), .Q
       (input_mux_out_w[0]));
  DF3 \bist_misr_dff_reg[1] (.C (clock), .D (n_134), .Q
       (signature_out[1]), .QN (UNCONNECTED4));
  NAND22 g1914(.A (n_132), .B (n_50), .Q (n_134));
  AOI2111 g1915(.A (n_131), .B (bist_controller_ncounter[9]), .C
       (n_129), .D (n_49), .Q (n_133));
  DFS1 \bist_lfsr_dff_reg[2] (.C (clock), .D (lsfr_in_bus_w[1]), .SD
       (lfsr_seed[2]), .SE (reset), .Q (lsfr_in_bus_w[2]), .QN
       (UNCONNECTED5));
  XNR21 g1917(.A (signature_out[0]), .B (grant_o[2]), .Q (n_132));
  DF3 \bist_misr_dff_reg[0] (.C (clock), .D (n_130), .Q
       (signature_out[0]), .QN (UNCONNECTED6));
  NAND22 g1919(.A (n_162), .B (n_127), .Q (n_131));
  DFS1 \bist_lfsr_dff_reg[1] (.C (clock), .D (lfsr_seed[1]), .SD
       (lsfr_in_bus_w[0]), .SE (n_50), .Q (lsfr_in_bus_w[1]), .QN
       (UNCONNECTED7));
  NOR22 g1921(.A (n_148), .B (n_49), .Q (scan_toggle_w));
  NAND22 g1922(.A (n_126), .B (n_50), .Q (n_130));
  OAI311 g1923(.A (bist_controller_ncounter[4]), .B
       (bist_controller_ncounter[5]), .C (bist_controller_ncounter[6]),
       .D (bist_controller_ncounter[7]), .Q (n_162));
  AOI211 g1925(.A (bist_controller_ncounter[9]), .B
       (bist_controller_ncounter[8]), .C
       (bist_controller_ncounter[10]), .Q (n_160));
  INV3 g1926(.A (n_49), .Q (bist_controller_n_114));
  NAND31 g1927(.A (n_122), .B (bist_controller_state[1]), .C
       (bist_controller_state[0]), .Q (n_49));
  OAI2111 g1928(.A (bist_controller_ncounter[1]), .B
       (bist_controller_ncounter[2]), .C (bist_controller_ncounter[3]),
       .D (bist_controller_ncounter[7]), .Q (n_127));
  IMUX21 g1929(.A (signature_out[7]), .B (n_123), .S (grant_o[3]), .Q
       (n_126));
  NAND22 g1931(.A (bist_controller_ncounter[7]), .B
       (bist_controller_ncounter[6]), .Q (n_153));
  INV3 g1932(.A (n_125), .Q (n_154));
  NAND22 g1933(.A (bist_controller_ncounter[3]), .B
       (bist_controller_ncounter[2]), .Q (n_125));
  INV3 g1934(.A (reset), .Q (n_50));
  DF3 \bist_controller_ncounter_reg[9] (.C (clock), .D (n_121), .Q
       (bist_controller_ncounter[9]), .QN (n_47));
  DF3 \bist_controller_ncounter_reg[7] (.C (clock), .D (n_120), .Q
       (bist_controller_ncounter[7]), .QN (n_43));
  NOR21 g2002(.A (n_67), .B (n_119), .Q (n_121));
  DF3 \bist_controller_ncounter_reg[10] (.C (clock), .D (n_117), .Q
       (bist_controller_ncounter[10]), .QN (UNCONNECTED8));
  DF3 \bist_controller_ncounter_reg[8] (.C (clock), .D (n_118), .Q
       (bist_controller_ncounter[8]), .QN (n_44));
  NOR21 g2005(.A (n_67), .B (n_116), .Q (n_120));
  IMUX20 g2006(.A (bist_controller_ncounter[9]), .B (n_112), .S
       (bist_controller_n_114), .Q (n_119));
  DF3 \bist_controller_ncounter_reg[6] (.C (clock), .D (n_115), .Q
       (bist_controller_ncounter[6]), .QN (UNCONNECTED9));
  NOR21 g2008(.A (n_67), .B (n_114), .Q (n_118));
  NOR21 g2009(.A (n_67), .B (n_113), .Q (n_117));
  IMUX20 g2010(.A (bist_controller_ncounter[7]), .B (n_110), .S
       (bist_controller_n_114), .Q (n_116));
  NOR21 g2011(.A (n_67), .B (n_111), .Q (n_115));
  IMUX20 g2012(.A (bist_controller_ncounter[8]), .B (n_109), .S
       (bist_controller_n_114), .Q (n_114));
  IMUX20 g2013(.A (bist_controller_ncounter[10]), .B (n_166), .S
       (bist_controller_n_114), .Q (n_113));
  IMUX20 g2014(.A (n_47), .B (bist_controller_ncounter[9]), .S (n_108),
       .Q (n_112));
  IMUX20 g2015(.A (bist_controller_ncounter[6]), .B (n_106), .S
       (bist_controller_n_114), .Q (n_111));
  IMUX20 g2016(.A (n_43), .B (bist_controller_ncounter[7]), .S (n_105),
       .Q (n_110));
  ADD22 g2017(.A (n_99), .B (bist_controller_ncounter[8]), .CO (n_108),
       .S (n_109));
  DF3 \bist_controller_ncounter_reg[5] (.C (clock), .D (n_104), .Q
       (bist_controller_ncounter[5]), .QN (UNCONNECTED10));
  ADD22 g2020(.A (n_95), .B (bist_controller_ncounter[6]), .CO (n_105),
       .S (n_106));
  DF3 bist_controller_toggle_r_reg(.C (clock), .D (n_102), .Q
       (bist_controller_toggle_r), .QN (n_148));
  NOR21 g2022(.A (n_67), .B (n_101), .Q (n_104));
  DF3 \bist_controller_ncounter_reg[3] (.C (clock), .D (n_98), .Q
       (bist_controller_ncounter[3]), .QN (n_45));
  NOR21 g2025(.A (n_67), .B (n_97), .Q (n_102));
  IMUX20 g2026(.A (bist_controller_ncounter[5]), .B (n_94), .S
       (bist_controller_n_114), .Q (n_101));
  DF3 \bist_controller_ncounter_reg[4] (.C (clock), .D (n_93), .Q
       (bist_controller_ncounter[4]), .QN (UNCONNECTED11));
  NOR21 g2029(.A (n_153), .B (n_96), .Q (n_99));
  NOR21 g2030(.A (n_67), .B (n_92), .Q (n_98));
  IMUX20 g2031(.A (bist_controller_toggle_r), .B (n_90), .S
       (bist_controller_n_114), .Q (n_97));
  INV2 g2032(.A (n_95), .Q (n_96));
  ADD22 g2033(.A (n_82), .B (bist_controller_ncounter[5]), .CO (n_95),
       .S (n_94));
  DF3 \bist_controller_ncounter_reg[2] (.C (clock), .D (n_91), .Q
       (bist_controller_ncounter[2]), .QN (UNCONNECTED12));
  NOR21 g2035(.A (n_67), .B (n_89), .Q (n_93));
  IMUX20 g2036(.A (bist_controller_ncounter[3]), .B (n_86), .S
       (bist_controller_n_114), .Q (n_92));
  DF3 \bist_controller_state_reg[0] (.C (clock), .D (n_88), .Q
       (bist_controller_state[0]), .QN (UNCONNECTED13));
  NOR21 g2038(.A (n_67), .B (n_87), .Q (n_91));
  AOI2111 g2039(.A (n_85), .B (bist_controller_ncounter[9]), .C
       (n_129), .D (bist_controller_toggle_r), .Q (n_90));
  IMUX20 g2040(.A (bist_controller_ncounter[4]), .B (n_83), .S
       (bist_controller_n_114), .Q (n_89));
  DF3 \bist_controller_state_reg[1] (.C (clock), .D (n_84), .Q
       (bist_controller_state[1]), .QN (UNCONNECTED14));
  OAI2111 g2042(.A (reset), .B (n_71), .C (n_78), .D (n_68), .Q (n_88));
  IMUX20 g2043(.A (bist_controller_ncounter[2]), .B (n_81), .S
       (bist_controller_n_114), .Q (n_87));
  IMUX20 g2044(.A (n_45), .B (bist_controller_ncounter[3]), .S (n_80),
       .Q (n_86));
  DF3 \bist_controller_ncounter_reg[1] (.C (clock), .D (n_79), .Q
       (bist_controller_ncounter[1]), .QN (n_42));
  DFS1 \bist_lfsr_dff_reg[0] (.C (clock), .D (n_69), .SD
       (lfsr_seed[0]), .SE (reset), .Q (lsfr_in_bus_w[0]), .QN
       (UNCONNECTED15));
  DFE1 bist_controller_bist_end_reg(.C (clock), .D (n_52), .E (n_72),
       .Q (bist_end), .QN (UNCONNECTED16));
  OAI212 g2048(.A (n_43), .B (n_77), .C (n_162), .Q (n_85));
  OAI212 g2049(.A (n_62), .B (n_54), .C (n_78), .Q (n_84));
  ADD22 g2050(.A (n_74), .B (bist_controller_ncounter[4]), .CO (n_82),
       .S (n_83));
  ADD22 g2051(.A (n_64), .B (bist_controller_ncounter[2]), .CO (n_80),
       .S (n_81));
  DF3 \bist_controller_state_reg[2] (.C (clock), .D (n_76), .Q
       (bist_controller_state[2]), .QN (n_122));
  NOR21 g2053(.A (n_67), .B (n_75), .Q (n_79));
  OAI2111 g2054(.A (n_57), .B (n_65), .C (bist_controller_n_114), .D
       (n_71), .Q (n_78));
  DF3 \bist_controller_ncounter_reg[0] (.C (clock), .D (n_70), .Q
       (bist_controller_ncounter[0]), .QN (n_46));
  AOI211 g2056(.A (n_53), .B (bist_controller_ncounter[3]), .C (n_154),
       .Q (n_77));
  NOR40 g2057(.A (reset), .B (n_57), .C (n_65), .D (n_49), .Q (n_76));
  IMUX20 g2058(.A (bist_controller_ncounter[1]), .B (n_63), .S
       (bist_controller_n_114), .Q (n_75));
  DFS1 bist_controller_reset_latch_reg(.C (bist_start), .D (reset), .SD
       (n_50), .SE (bist_start), .Q (bist_controller_reset_latch), .QN
       (UNCONNECTED17));
  INV2 g2060(.A (n_73), .Q (n_74));
  NAND22 g2061(.A (n_64), .B (n_154), .Q (n_73));
  NAND22 g2062(.A (n_66), .B (n_48), .Q (n_72));
  AOI211 g2063(.A (n_54), .B (n_59), .C (reset), .Q (n_71));
  NOR21 g2064(.A (n_67), .B (n_56), .Q (n_70));
  XOR31 g2065(.A (lsfr_in_bus_w[2]), .B (lsfr_in_bus_w[3]), .C
       (signature_out[7]), .Q (n_69));
  NAND22 g2066(.A (bist_controller_state[1]), .B (n_61), .Q (n_68));
  INV3 g2067(.A (n_66), .Q (n_67));
  AOI211 g2068(.A (n_54), .B (bist_controller_state[2]), .C (reset), .Q
       (n_66));
  NAND22 g2069(.A (n_58), .B (n_60), .Q (n_65));
  ADD22 g2070(.A (bist_controller_ncounter[1]), .B
       (bist_controller_ncounter[0]), .CO (n_64), .S (n_63));
  DF3 \bist_misr_dff_reg[7] (.C (clock), .D (n_55), .Q
       (signature_out[7]), .QN (n_123));
  INV2 g2072(.A (n_61), .Q (n_62));
  NOR31 g2073(.A (bist_controller_n_114), .B
       (bist_controller_state[2]), .C (reset), .Q (n_61));
  NOR31 g2074(.A (bist_controller_ncounter[0]), .B
       (bist_controller_ncounter[10]), .C
       (bist_controller_ncounter[2]), .Q (n_60));
  NOR31 g2075(.A (bist_controller_state[2]), .B
       (bist_controller_reset_latch), .C (n_48), .Q (n_59));
  NOR40 g2076(.A (bist_controller_ncounter[4]), .B
       (bist_controller_ncounter[5]), .C (bist_controller_ncounter[6]),
       .D (n_45), .Q (n_58));
  NAND41 g2077(.A (n_44), .B (bist_controller_ncounter[7]), .C
       (bist_controller_ncounter[9]), .D (bist_controller_ncounter[1]),
       .Q (n_57));
  IMUX21 g2078(.A (bist_controller_n_114), .B (n_49), .S
       (bist_controller_ncounter[0]), .Q (n_56));
  NAND22 g2079(.A (n_51), .B (n_50), .Q (n_55));
  NOR21 g2080(.A (bist_controller_state[0]), .B
       (bist_controller_state[1]), .Q (n_54));
  NAND22 g2081(.A (n_42), .B (n_46), .Q (n_53));
  NOR20 g2082(.A (bist_start), .B (reset), .Q (n_52));
  INV2 g2120(.A (bist_start), .Q (n_48));
  IMUX20 g2303(.A (n_35), .B (n_9), .S (n_27), .Q (uut_n_110));
  IMUX20 g2304(.A (n_34), .B (n_1), .S (n_27), .Q (uut_n_111));
  IMUX20 g2305(.A (n_33), .B (n_7), .S (n_27), .Q (uut_n_108));
  IMUX20 g2306(.A (n_37), .B (n_4), .S (n_27), .Q (uut_n_107));
  IMUX20 g2307(.A (n_39), .B (n_2), .S (n_27), .Q (uut_n_105));
  IMUX20 g2308(.A (n_36), .B (n_3), .S (n_27), .Q (uut_n_106));
  INV3 g2309(.A (n_41), .Q (uut_n_103));
  INV3 g2310(.A (n_40), .Q (uut_n_102));
  INV3 g2311(.A (n_38), .Q (uut_n_104));
  OAI211 g2312(.A (n_4), .B (n_30), .C (n_29), .Q (uut_n_87));
  OAI211 g2313(.A (n_3), .B (n_30), .C (n_28), .Q (uut_n_89));
  AOI221 g2314(.A (n_31), .B (uut_coda3[0]), .C (n_27), .D
       (uut_coda2[0]), .Q (n_41));
  AOI221 g2315(.A (n_31), .B (uut_coda3[1]), .C (n_27), .D
       (uut_coda2[1]), .Q (n_40));
  OAI222 g2316(.A (n_31), .B (uut_coda2[0]), .C (uut_n_98), .D
       (uut_coda1[0]), .Q (n_39));
  AOI221 g2317(.A (n_31), .B (uut_coda3[2]), .C (n_27), .D
       (uut_coda2[2]), .Q (n_38));
  OAI222 g2318(.A (n_31), .B (uut_coda2[1]), .C (uut_n_98), .D
       (uut_coda1[1]), .Q (n_37));
  OAI222 g2319(.A (n_31), .B (uut_coda2[2]), .C (uut_n_98), .D
       (uut_coda1[2]), .Q (n_36));
  OAI222 g2320(.A (n_31), .B (uut_coda3[0]), .C (uut_n_98), .D
       (uut_coda2[0]), .Q (n_35));
  OAI222 g2321(.A (n_31), .B (uut_coda3[1]), .C (uut_n_98), .D
       (uut_coda2[1]), .Q (n_34));
  OAI222 g2322(.A (n_31), .B (uut_coda3[2]), .C (uut_n_98), .D
       (uut_coda2[2]), .Q (n_33));
  OAI2111 g2323(.A (n_9), .B (n_24), .C (n_32), .D (n_23), .Q
       (uut_n_84));
  NAND22 g2324(.A (n_31), .B (uut_coda0[0]), .Q (n_32));
  INV2 g2325(.A (n_31), .Q (n_30));
  OAI2111 g2326(.A (uut_n_98), .B (uut_n_73), .C (n_26), .D (n_19), .Q
       (n_31));
  AOI2111 g2327(.A (uut_n_98), .B (uut_coda1[1]), .C (n_22), .D (n_21),
       .Q (n_29));
  AOI2111 g2328(.A (uut_n_98), .B (uut_coda1[2]), .C (n_14), .D (n_21),
       .Q (n_28));
  NAND22 g2329(.A (n_23), .B (n_25), .Q (n_27));
  AOI221 g2330(.A (n_18), .B (n_20), .C (n_15), .D (uut_fu2), .Q
       (n_26));
  NOR21 g2331(.A (n_14), .B (n_22), .Q (n_25));
  INV3 g2332(.A (n_24), .Q (uut_n_98));
  NAND31 g2333(.A (uut_stato[0]), .B (n_13), .C (uut_stato[1]), .Q
       (n_24));
  AOI311 g2334(.A (n_6), .B (uut_ru3), .C (n_18), .D (n_21), .Q (n_23));
  NOR21 g2335(.A (uut_fu2), .B (n_16), .Q (n_22));
  NOR31 g2336(.A (n_17), .B (n_10), .C (uut_ru3), .Q (n_21));
  MUX22 g2337(.A (n_10), .B (uut_fu3), .S (uut_ru3), .Q (n_20));
  NOR31 g2338(.A (n_3), .B (n_2), .C (n_4), .Q (uut_n_63));
  NAND31 g2339(.A (uut_n_73), .B (uut_ru1), .C (uut_fu1), .Q (n_19));
  INV2 g2340(.A (n_18), .Q (n_17));
  NOR31 g2341(.A (n_11), .B (uut_ru1), .C (uut_ru2), .Q (n_18));
  NOR31 g2342(.A (n_3), .B (uut_coda0[0]), .C (uut_coda0[1]), .Q
       (uut_n_61));
  NOR31 g2343(.A (n_4), .B (uut_coda0[2]), .C (uut_coda0[0]), .Q
       (uut_n_60));
  NOR31 g2344(.A (n_2), .B (uut_coda0[2]), .C (uut_coda0[1]), .Q
       (uut_n_59));
  INV2 g2345(.A (n_15), .Q (n_16));
  NOR31 g2346(.A (n_11), .B (n_8), .C (uut_ru1), .Q (n_15));
  NOR31 g2347(.A (n_11), .B (n_5), .C (uut_fu1), .Q (n_14));
  INV3 g2348(.A (n_12), .Q (n_13));
  NOR40 g2349(.A (uut_fu4), .B (uut_fu3), .C (uut_fu1), .D (uut_fu2),
       .Q (n_12));
  INV2 g2350(.A (uut_n_73), .Q (n_11));
  NOR21 g2351(.A (uut_stato[1]), .B (uut_stato[0]), .Q (uut_n_73));
  NAND22 g2352(.A (n_0), .B (uut_ru4), .Q (n_10));
  INV2 g2353(.A (uut_coda1[0]), .Q (n_9));
  INV2 g2354(.A (uut_ru2), .Q (n_8));
  INV2 g2355(.A (uut_coda1[2]), .Q (n_7));
  CLKIN2 g2356(.A (uut_fu3), .Q (n_6));
  INV2 g2357(.A (uut_ru1), .Q (n_5));
  CLKIN3 g2358(.A (uut_coda0[1]), .Q (n_4));
  CLKIN3 g2359(.A (uut_coda0[2]), .Q (n_3));
  INV2 g2360(.A (uut_coda0[0]), .Q (n_2));
  INV2 g2361(.A (uut_coda1[1]), .Q (n_1));
  INV2 g2362(.A (uut_fu4), .Q (n_0));
  XNR21 g2(.A (n_165), .B (bist_controller_ncounter[10]), .Q (n_166));
  NAND31 g3(.A (bist_controller_ncounter[9]), .B
       (bist_controller_ncounter[8]), .C (n_99), .Q (n_165));
endmodule

